name: Update VSCode extension

on:
  workflow_dispatch:
  push:

jobs:
  bump-vsc-package:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 16


      - name: Generate GitHub App token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get latest code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ steps.app_token.outputs.token }}


      - name: Bump package version
        uses: jpb06/bump-package@latest
        with:
          major-keywords: BREAKING CHANGE
          minor-keywords: feat
          should-default-to-patch: true

      - run: yarn install --frozen-lockfile

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
