name: Update submodules

on:
  workflow_dispatch:
  schedule:
    - cron: 10 0 * * SUN

jobs:
  update-submodules:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get latest code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ steps.app_token.outputs.token }}


      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          push: true
          default_author: github_actions
          message: 'ci: update submodules'
