name: Update submodules

on:
  workflow_dispatch:
  schedule:
    - cron: 10 0 * * SUN

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT_TOKEN }}
          submodules: true


      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          push: true
          default_author: github_actions
          message: 'ci: update submodules'
